# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Mean function
#' @description calculate mean of vcector x
#' @param x vector
#' @return mean(double)\code{n}
#' @export
meanC <- function(x) {
    .Call('_StatComp20008_meanC', PACKAGE = 'StatComp20008', x)
}

